# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd792520505833fc59fa4a67ee2c821ea4e0395633344daf0388f8cc4666cba2c850d7ec36e56f7149328db8fa7824b09cdaf17984cac6419ae365bbfa423ce
  guides_access_token: <%= ENV["GUIDES_ACCESS_TOKEN"] %>
  dragonfly_secret: d39ec11719d234a96c208515c77b4945b299629f398364985329b9bdab20f618f71ed28297065a5c080c6a9448a5d5725135fd2546e367accbdbe16c3ad4a9b5

test:
  secret_key_base: 0365a2f6be8f7bb78b02fa5379227ad3dfdaa660987f807f7dbd6586b663968b4f8533c3bc7d089faf94e207e6a72c1fb57b897a3af9297ad5e90507d6259332
  guides_access_token: <%= ENV["GUIDES_ACCESS_TOKEN"] %>
  dragonfly_secret: 4324482890d63d8a80d96db5a298e81b431937eabd2806f0186021f18a612619c71344182578527be42f0433e288e9c27d4341497b87a83e63edda280862ef5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  guides_access_token: <%= ENV["GUIDES_ACCESS_TOKEN"] %>
  dragonfly_secret: <%= ENV["DRAGONFLY_SECRET"] %>
